version: "3"

services:
    seedemu-client:
        build: .
        container_name: seedemu_client
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - 8080:8080

        networks:
            - my-network
networks:
    my-network:
        driver: bridge
